### ISSUE TITLE
Маркировки

### ISSUE THREAD

**Issue by Galstuk** [Kucherlogrus/woc-arcanoid#10]
Переезд на гитхаб осуществлен.
Ввели разделение тем метками:
Красый - Слава
Синий - Виталик
Зеленый - Саша

Всем на ознакомление

**Comment by Galstuk** [comment]
Всем на ознакомление и тестирование.

**Comment by Kucherlogrus** [comment]
ok

**Comment by vitswat** [comment]
Тема закрыта
